sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: RSs4E1C4BzMH2K9TIkM7vjoZD2e0H3JVPL8nSwHnW94na6OlzCYh4BaQILaKMnETsZepxECVZH2Ud6EIQLDr9aYjhbfajccUmqd13mru5FbPL+OSvE0pmHcEjGNfkwg/EAtt+KQ0nISNTfCLmgZJRXk4CU/J2wAgz0Tscj6/9w402WymHyvsYSh1uUocWGnqKeUogdPaKQTJP9MO4GYnbj/XF93V9obd6Hlw8hRebFZUhtmaUsX5lH2pX7yriXdNNUUKl0wI7SSXIXay6eimsrK1ZpDdARzzMpvscoj+WxA+f3uh53IXtW23BuKqsEEtP7OAv2KJd9gJ51DUSJPJSKT0PuFsqnqsPoyNG+4+FW5TwybXJbgHImIHvPpwZkKRT7g4COmhptTx7OX35nU3SHX1+YqZme+WrCfxBOxiQKqJIo2WvcPDctcHZ/MQnqDxaLF2NrK26u1H1TgJ+84QAStVLOqKJYNPiOmUwtqljniAFg5B73kq/200qS+BGIGs21UmHh3PAnYrRCDbirUjAqD85Gtm8gAzlNUHdosPGEZc2/BPrL6HPS4/MoLudf76KasDJ5Lza1TQy2DKoIDYVwVnCkrk1NFlhJb/owPaGcXUVm/NDV3nm2I4qaxEynbqERvE1kB1Mv5zGE+Pdo26vldWdmrIjo5QuwJY7dLLtC0=
  - secure: rJSXG0S2uk3RjngQv9NK3jgHR4LYsHiyh7GU2jo8XBgxIqY0ffBGvXHatw3/t3ycv7/roE3wzlRO/+kdIqODzxQDETq4wQxxIy+YtBS6U4MeXDfuv85TGgCjz6rvsbkx+/qQbuJGzelJzbWNq6/BxVs4n3Yf8hGlAKX1YPnCaiQNh0E28FTsidUMohV7N8nI58qtWQWKPNfRQBviDm0JkyOl846KTL1nzbQaY2PWqV0lfLBQxhrbpcj/DgjVvzGRYD7GvudZNR/FGfYykPHHMeHK3o2P/UIncfvvs9DY+pw8/YmVJdCRz0iuXM9kQS3WG3CDO6W+CcpXv7BHkogzNS7P2OYlBT3wJNXxlGrcWPPuGvGBgV2BJvJDxwoj+pp7RMhh+vQETY/Jo1v7jCw1h4bjL69a3xCbpHJJmXqY49JpdOnb9GD+WVUkbq9snPVn7OkeCEqFytf8S4pJOxT1Tve0UyrhghtyxZTWcOzqi7HI/NW1U+mBLHtuX7/p845Hz1O8sx1Ly4ngmDp5/PO8ETl93dYJZeTB2IshZdq8BveKcL+yMlHocknY7usCCgRGhbpbW/zXgW6Do4aWDPGpC9CAG3rdL9CJCgEtrHztV5NciBaDAP9w9ergqoABAU+X/CQA6cBn0B9AgrZU4bAy7em8c9n3TRXCooCS/7yvBQU=
  - secure: irq/zqfk9G+LqeW7ruURu+qb62Eqexw6KexbPpcKx9/8uUKbpu/uLdrI6JYM67XCQEg7Sw4V4EyEdqmNoBMfgvr8/l3kkVzlJSNxqJlMjLOMNcjSiJP9hRyrUTpRzfIaCH61KoKmjMu8vIjFSkcHFFA6xTqh866DSwUkyMqXELpOsFmK3Dd+RXsGfl6aitJ5JKYoua4rr+/8PXQ2EkeM3hZKx9a7DHp/H/BRHrlwBHDNCo2uQIuzmxm18bcz7JpQPqTiBdBpaRDicFx4/PU++tglz5nWh54yKgbkrWhgZw4yko28o58rn8DQcjt7leM9lIBof+FG96xaDBFrwRbD+MnDfRJoy31cBFZPHdgWdRcPMktgmVQNrVkGEhWThg2jEnMGXs03gJ/Ya7qL58Nur/t0reaOoTJN1IjEWR6nk8IcsVsA8S6tDn0PXuNs51pQUaOS6Vp2iTnWX3nOawW5/TP4iAmsvcNOTjxapChfqZkasZ2q/KJNz+KgX/O95hi0s5Z8E5QUnmxNRBfFLszXgD8PPVaXGDGIqr0KmarOnRUHBOAEx9sRL6sGrF9500jy1+0Nxlm1YhKtx5hANCxutjsW5RWGuBpgXFxbs2+zMRfrMJrG/1JLtPEiR7zbUTsg9QqHYj9WtmZR+mX1RXZT9ua7RpJkya0En5AIPJYN58w=
  - secure: TWwCPOdW4w0KHHLj1aWNsUR2f4C3Kkg8Tk7uR3KO3NruhWvXQ6OOi3jo8JHO4yp1Qdq6lI0UayHa8qsOwBpAEPYoRzqWflbRkkXXlM47gWk3ShLCu3YyyxR/JOcGjS6O/Fpxgi/kDVz8QR2VvJrVvXmFKBeMl4Wcl9x3e68Q2yp447xGTnhqIEKl/Fi5IIusuY9Qzwg29k0O3jB02K3fPcpGDJRt5dssGJFQzsi4xciE5Pq6fz2OGmLcAfVGjQYUDvWMCEx2A8M8b2KaEeyG8G4wTfUpgy1CKKAcMQEF1lzEdhgE0wQzeSJ95Vyqn8nAdiNdvjGTjY4mC7fquqclAPwSlUkTIEodApJ2K+Ssofac4fnAD8nLOQ6GI+BQau92fC2Wb8OL067f1UOBDbTSdu6LiK9tHqec2RiTF9sN9vcE7YVnaiCVutFF0iYmx1L8Q/jXBzPhfebt6tD5V53w5rtRHSE+E4TCTm+rgB2ZjfRSeWs8pKZW8bqd9hmivgy5FNBpzc4/52pX9C6QavNx3NMdWqZTmX4BXe0ZG9ofOdJiGQJzmapOXZMO2l22tn05kd37X2jw/Df5jQZ4QtDvM87FuSO7LKJvPDJN3kQqFLjCulJwRo6rlejEb+cTFZINQI+AxkC11vtxDaJuOHJ57jMzXBsqibwmcUqqO2bv+I4=
  - secure: VRDd8/maikEBTWq9Uxb8HBfWps+/HeEkofggk/BCTnTYVzWR2Fkt6v8Q7Y0pXfRIBTRbee75i/ucvaqm5cwz69FJc7aUnmqD1/UqlG0QBqV5TNKHxzwlybkFwVMlsMLTdgrIPFZBCWSbaNpl22k7SHo8k12zSABOoLpfRUwv6bP0+Iz6+VEQl65vEb0HVJbv8Gl9c58FOEYA+jFWAdIn8loIl98t/ZSTvAv5JJDh7DFXEtaESgVboLfFS6Dwo2xJRwxBtz4JjFKByOMCigqBHO2zdCK1wNoa2MqH1xfOlgh/0UYT9h59R0lukj64lVaPbV0mra9cWfprUDUl0O9WLrwS8AOzs0QLwyI5aTb2O32EJh585PiGtrBtxNCs6blqPhNbtfyPTIZHoSVW3KpELPHLLrcy8cXaVm+cqfbP1CUHgplfoAnN1zAomrMFsdz358NVsf4ihTD2bJDDcPUBP2mSllxYOOTWQhqSakYSt0R+afPYCT/ySMEkqH50vh+nnLONxL3oLgQk786br/M9nOkmsgPzL5zgC07flW4RouOMMkbUohzqEVolvFtHdMlvGRMiuq1SvCzLTqhLE5pxA3q7U5Bakb8f4EYfvFfpwUHkodi0YeL9eh2+NZx56DmxtQgRNR6acL+VYOVj4f9ZsAsYATyCLOL4OvXJMTDsdEE=
